steps:
- task: XamariniOS@2
  displayName: 'Build Xamarin.iOS solution **/*.sln'
  inputs:
    solutionFile: '**/*.sln'
    configuration: 'Debug'
    packageApp: false
    buildForSimulator: true
    runNugetRestore: true
