pool:
  name: Hosted macOS High Sierra
  demands: Xamarin.iOS

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: XamariniOS@2
  displayName: 'Build Xamarin.iOS solution **/*.sln'
  inputs:
    clean: true
    packageApp: false
    buildForSimulator: true
