resources:
- repo: self

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'

  steps:
  - task: XamariniOS@2
    displayName: 'Build Xamarin.iOS solution **/*.sln'
    inputs:
      solutionFile: '**/*.sln'
      configuration: 'Release'
      packageApp: false
      buildForSimulator: false
      runNugetRestore: true
  - script: 'nuget pack *.nuspec -Properties Configuration=Release'
    displayName: Pack library
  - task: CopyFiles@2
    inputs:
      contents: '*.nupkg'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: 'drop'
