resources:
- repo: self

trigger: none

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'

  steps:
  - script: 'msbuild src/MapBoxBindingIOS.csproj -t:rebuild /p:Configuration=Release'
    displayName: Build library
  - script: 'nuget pack *.nuspec -Properties Configuration=Release'
    displayName: Pack library
  - task: CopyFiles@2
    inputs:
      contents: '*.nupkg'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: 'drop'
